### ISSUE TITLE
Is the evaluation process supporting batching ?

### ISSUE THREAD

**Issue by GeneZC** [hijkzzz/alpha-zero-gomoku#1]

**Comment by hijkzzz** [comment]
如果您指的是MCTS里面的evaluation吗？
libtorch多线程调用GPU预测是串行执行的，调用CPU是并行的
刚更新的代码默认用CPU预测

**Comment by GeneZC** [comment]
我是指mcts在evaluation时batch_size是为1吗？

**Comment by hijkzzz** [comment]
> 我是指mcts在evaluation时batch_size是为1吗？

对的
