### ISSUE TITLE
ImportError: ../build/_library.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

### ISSUE THREAD

**Issue by chinesealex** [hijkzzz/alpha-zero-gomoku#10]
I successfully compiled the library on ubuntu 18.04, but encountered the undefined symbol problem. Could you help me to solve the problem?

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "leaner_test.py", line 6, in <module>
    import learner
  File "../src/learner.py", line 17, in <module>
    from library import MCTS, Gomoku, NeuralNetwork
  File "../build/library.py", line 15, in <module>
    import _library
ImportError: ../build/_library.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

Thank you very much

**Comment by hijkzzz** [comment]
I precompiled binary files for Ubuntu.
Please see Release page.
