### ISSUE TITLE
训练线程数是否能尽量大

### ISSUE THREAD

**Issue by abdxyz** [hijkzzz/alpha-zero-gomoku#11]
你好，是否可以在机器允许的情况下，把训练线程数增大。
当线程数很大时，是否会很多线程都在等gpu返回计算结果，训练时间并不会明显减少

**Comment by abdxyz** [comment]
我试了下，线程数10,25,50最后总用时差不多的。线程大时，会大量占用系统内存。这样的话，线程太多反而不太好

**Comment by hijkzzz** [comment]
這個和機器性能關係較大~
