### ISSUE TITLE
Value loss doesn't decrease

### ISSUE THREAD

**Issue by chinesealex** [hijkzzz/alpha-zero-gomoku#12]
Hi hijkzzz,

I really appreciate the value of your work.

Currenly I'm trying to reimplement your work in pure c++ to accomodate my project's need. But after I reimplement your code in c++, I found out that the value loss doesn't decrese at all after even ~2000 iterations and the policy loss decreases pretty fast from the very begining.

Have you met any similar issue when you develop your alphazero project? And could you give some suggestion of the cause of my issue based on your experience?

Many appericates
Alex

**Comment by hijkzzz** [comment]
Maybe your algorithm is over-fitting?
