### ISSUE TITLE
运行速度问题

### ISSUE THREAD

**Issue by captiontimo** [hijkzzz/alpha-zero-gomoku#13]
使用百度云盘上下载模型，再使用人机对战，发现电脑大概计算5分钟才会下一子。
这个速度正常吗？（用的是至强CPU，主频2.1，8核）
有什么办法加快速度吗？

**Comment by hijkzzz** [comment]
沒有GPU？那就只能減少搜索次数了，需要修改play的代码。

**Comment by captiontimo** [comment]
您好，谢谢解答！
我一开始是用GPU的，但是每次learner调用neural_network的时候，pytorch都会报错，from torch._C import *找不到指定模块（运行其他代码都可以用Cuda正常加速）。然后我才用CPU的。
但是我今天晚上发现，在learner_test里加一句import torch，这个问题就解决了，然后GPU就可以加速了。
