### ISSUE TITLE
ITER：：1后直接闪退

### ISSUE THREAD

**Issue by kemolo** [hijkzzz/alpha-zero-gomoku#15]
"""
执行到此处开始闪退，f.result()无法执行，没有报错
环境 
win10
python 3.7
libtorch 1.3.1
pytorch 1.3.1

"""
#learner.py
 with concurrent.futures.ThreadPoolExecutor(max_workers=self.num_train_threads) as executor:
                futures = [executor.submit(self.self_play, 1 if itr % 2 else -1, libtorch, k == 1) for k in 
           range(1, self.num_eps + 1)]
               
                for k, f in enumerate(futures):
                    examples = f.result()
                    itr_examples += examples
                    # decrease libtorch batch size
                    remain = min(len(futures) - (k + 1), self.num_train_threads)
                    libtorch.set_batch_size(max(remain * self.num_mcts_threads, 1))
                    
                    print("EPS: {}, EXAMPLES: {}".format(k + 1, len(examples)))

**Comment by kemolo** [comment]
已解决
编译之前
libtorch.cpp 第11行
改成  module(std::make_shared<torch::jit::script::Module>(torch::jit::load(model_path.c_str())))
可顺利通过

**Comment by hijkzzz** [comment]
已经加上显示转换
