### ISSUE TITLE
关于并行的问题

### ISSUE THREAD

**Issue by CainHu** [hijkzzz/alpha-zero-gomoku#17]
你好，我看了下描述，有10个仿真，每个仿真有4个线程搜索。我想问一下，每个仿真里都是公用变量的吗，比如说n_visited，还是说每个仿真都是独立的？GPU的神经网络是同时接受10个棋谱，还是4个，还是40啊？

**Comment by hijkzzz** [comment]
是40个

**Comment by hijkzzz** [comment]
是有锁的公用变量，是40个

**Comment by CainHu** [comment]
相当于收集到了40个棋局，再推送到神经网络里进行计算，那为什么神经网络要通过C++做前端呀。c++负责收集40个棋局，收集齐了之后，再给python的神经网络计算不是也可以吗？

**Comment by hijkzzz** [comment]
本来打算纯C++写的，后来为了方才用python写了。实际上是可以直接调python的不用libtorch

**Comment by CainHu** [comment]
好的 谢谢！
