### ISSUE TITLE
你好，请问你的项目在别的电脑上如何运行呢？

### ISSUE THREAD

**Issue by LLYYKK** [hijkzzz/alpha-zero-gomoku#18]
比起Python，C++环境的搭建实在是充满了困难。根据您有限的描述，实在难以让新手快速配置出可以运行您代码的环境。希望您如果有时间，可以完善一下这方面的信息，不胜感激。

**Comment by LLYYKK** [comment]
老哥啊，不知道你有没有试过在别的电脑上跑你的代码。在windows环境下，光是搭建环境就是一个接一个的坑啊，装这个装那个，每装一个东西都有坑。好不容易把东西都装好了，cmake build-- .也成功了(你上面的还少了".")。最后训练模型的时候还报错读取"_llbrary"失败？我也是服了，实在不知道该怎么办了。

**Comment by hijkzzz** [comment]
确实有点复杂~但是最近没有时间做简化诶。。。
建议下载Release里面编译好的文件直接使用
需要安装Pytorch Libtorch等组件放到环境变量中

**Comment by LLYYKK** [comment]
> 确实有点复杂~但是最近没有时间做简化诶。。。
> 建议下载Release里面编译好的文件直接使用
> 需要安装Pytorch Libtorch等组件放到环境变量中

你好，我是win10平台，请问对Pytorch和Libtorch的版本或配置上是否有具体要求呢？
我试过Libtorch1.4.0，1.1.0版本。Pytorch为1.4.0版本。
使用你编译好的文件，也依然会产生找不到_library的错误。
所以想请教一下是否有一些额外的设置呢？

**Comment by LLYYKK** [comment]
我需要把libtorch解压在什么位置呢？

**Comment by LLYYKK** [comment]
您好，我遇到的情况是这样的：win10平台下我直接下载你的Release版，也下载了libtorch放在了C盘根目录，也设置好了环境变量。然后去到test文件夹执行python learner_test.py train
有错误提示：
File "../build\library.py", line 15, in <module>
    import _library
ImportError: DLL load failed: 找不到指定的模块。

更换过不同版本的libtorch也是不行。
下载了VS2019、Cmake、SWIG 3.0.12并按照您的教程尝试编译，执行
“cmake .. -DCMAKE_PREFIX_PATH=path/to/libtorch -DCMAKE_BUILD_TYPE=Release”
“cmake --build .”
没有报错，也生成了library.py，但再去到test文件夹执行python learner_test.py train
依然找不到指定模块。

实在是被C++搞得一脸懵逼了，因此有如下问题想请问一下您。
1.我需要根据CMakeSeting.json里的参数做出什么修改吗？比如"cmakeCommandArgs"。
2.如果无法使用您提供的Release版本，最可能是什么原因导致的呢？
3.如果我想在windows上用cmake自行编译，需要如何进行操作呢？

期待您的回复。

**Comment by hijkzzz** [comment]
编译好的文件要放到 build目录下

**Comment by hijkzzz** [comment]
因为我是1.1版本编译的吧

**Comment by hijkzzz** [comment]
后面有空了再~ 改造这个项目 去掉LibTorch的依赖和繁琐的编译

**Comment by LLYYKK** [comment]
> 编译好的文件要放到 build目录下

谢谢您的回答！不过，您提供的Release版里面已经有build文件夹了呢，我没有动过它噢。

**Comment by hijkzzz** [comment]
编译好的版本是 PyTorch 1.1 + CUDA10.1 + Python3.7的 看看匹配不
还有就是要cd 到test目录下执行
