### ISSUE TITLE
ubuntu release 报错ImportError

### ISSUE THREAD

**Issue by Kekwi** [hijkzzz/alpha-zero-gomoku#19]
libtorch包，官网下载的
https://download.pytorch.org/libtorch/cu101/libtorch-shared-with-deps-1.5.0%2Bcu101.zip
环境变量
export PATH=$PATH:/home/xxx/libtorch

python 是用anaconda安装的，一下是一些主要库的版本
python3.7.6
cuda10.1
pytorch1.1

模型从度盘下载，放到项目的models目录下

运行
python leaner_test.py play
报错
Traceback (most recent call last):
  File "leaner_test.py", line 7, in <module>
    import learner
  File "../src/learner.py", line 14, in <module>
    from library import MCTS, Gomoku, NeuralNetwork
  File "../build/library.py", line 15, in <module>
    import _library
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

我还有什么地方没配置呢？

**Comment by hijkzzz** [comment]
libtorch也要是1.1 要不就自己编译咯

**Comment by hijkzzz** [comment]
很抱歉现在才看到，哈哈
