### ISSUE TITLE
Can it run on Ubuntu？

### ISSUE THREAD

**Issue by ShuttleDDD** [hijkzzz/alpha-zero-gomoku#2]
我在windows上经过一番折腾之后可以编译，在ubuntu上编译时就遇到了如下问题
(dl) root@d93dac271dfe:/input/alpha-zero-gomoku/build# cmake --build .
[ 16%] Built target library_swig_compilation
CMakeFiles/_library.dir/build.make:138: *** target pattern contains no '%'。 停止。
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/_library.dir/all' failed
make[1]: *** [CMakeFiles/_library.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hijkzzz** [comment]
理论上是可以的
用到的所有的第三方包都是跨平台的
只是可能版本/CMakeList需要改一改？
不过我暂时没有Ubuntu环境测试
