### ISSUE TITLE
How did you create SWIG for libtorch?

### ISSUE THREAD

**Issue by QuantScientist** [hijkzzz/alpha-zero-gomoku#20]
Also, is C++ calling Python or libtorch calling Python? 
I know you are loading the trained PT in Libtorch, but why do you need SWIG?

**Comment by hijkzzz** [comment]
Thanks for your attention.

SWIG wraps C++ modules such as mcts, thread pool to python interfaces.
The reason for this is that I don’t want to rewrite the UI and training code.
