### ISSUE TITLE
为什么pretrained model这么弱

### ISSUE THREAD

**Issue by robinwhy** [hijkzzz/alpha-zero-gomoku#25]
你好，感谢你的code，我试了试pretrained model，发现AI下的飘忽不定，而且连活三都不会堵，我执X，AI执O
<img width="863" alt="截屏2021-04-26 上午8 04 21" src="https://user-images.githubusercontent.com/37237526/116014127-489c2600-a666-11eb-9d6e-160770c0f0ad.png">
请问这个model训练了几局？有什么想法吗？

**Comment by hijkzzz** [comment]
我测试的时候是很强的（电脑先手必赢），或许您可以重新训练。因为第三方库版本已经发生了很多变化。
