### ISSUE TITLE
Link to the 1.5-day pre-trained models is broken.

### ISSUE THREAD

**Issue by drag0nglass** [hijkzzz/alpha-zero-gomoku#26]
Link to the 1.5-day pre-trained models is broken.
`https://pan.baidu.com/s/1c2Otxdl7VWFEXul-FyXaJA` says `啊哦，你来晚了，分享的文件已经被取消了，下次要早点哟。`.

**Comment by hijkzzz** [comment]
Hello 我的百度网盘被封了 所以模型不见啦~
