### ISSUE TITLE
版本

### ISSUE THREAD

**Issue by gms2009** [hijkzzz/alpha-zero-gomoku#27]
请问 ubuntu 用什么版本 还有 numpy
我用 libtorch-cxx11-abi-shared-with-deps-1.2.0.zip   和 torch 1.2.0
Segmentation fault (core dumped)
找不到合适的 libtorch 1.1.0

**Comment by hijkzzz** [comment]
ubuntu 版本不影响
当时测试环境为 pytorch1.1 + libtorch 1.1 + cuda10.1 +gcc 6+

**Comment by hijkzzz** [comment]
找到一个链接 https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-1.1.0.zip

**Comment by hijkzzz** [comment]
找到一个链接 cuda10的 https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-1.1.0.zip

**Comment by gms2009** [comment]
编译过不了
[ 33%] Building CXX object CMakeFiles/_library.dir/src/libtorch.cpp.o
In file included from /usr/include/x86_64-linux-gnu/c++/6/bits/c++allocator.h:33:0,
                 from /usr/include/c++/6/bits/allocator.h:46,
                 from /usr/include/c++/6/memory:63,
                 from /home/weilo/Videos/libtorch/include/c10/core/Allocator.h:4,
                 from /home/weilo/Videos/libtorch/include/ATen/ATen.h:3,
                 from /home/weilo/Videos/libtorch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/weilo/Videos/libtorch/include/torch/script.h:3,
                 from /home/weilo/Videos/alpha-zero-gomoku/./src/libtorch.h:3,
                 from /home/weilo/Videos/alpha-zero-gomoku/src/libtorch.cpp:1:
/usr/include/c++/6/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = torch::jit::script::Module; _Args = {std::shared_ptr<torch::jit::script::Module>}; _Tp = torch::jit::script::Module]’:
/usr/include/c++/6/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = torch::jit::script::Module; _Args = {std::shared_ptr<torch::jit::script::Module>}; _Tp = torch::jit::script::Module; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<torch::jit::script::Module>]’
/usr/include/c++/6/bits/shared_ptr_base.h:520:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::shared_ptr<torch::jit::script::Module>}; _Tp = torch::jit::script::Module; _Alloc = std::allocator<torch::jit::script::Module>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/6/bits/shared_ptr_base.h:615:4:   required from ‘std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = torch::jit::script::Module; _Alloc = std::allocator<torch::jit::script::Module>; _Args = {std::shared_ptr<torch::jit::script::Module>}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/6/bits/shared_ptr_base.h:1100:35:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<torch::jit::script::Module>; _Args = {std::shared_ptr<torch::jit::script::Module>}; _Tp = torch::jit::script::Module; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/usr/include/c++/6/bits/shared_ptr.h:319:64:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<torch::jit::script::Module>; _Args = {std::shared_ptr<torch::jit::script::Module>}; _Tp = torch::jit::script::Module]’
/usr/include/c++/6/bits/shared_ptr.h:619:14:   required from ‘std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = torch::jit::script::Module; _Alloc = std::allocator<torch::jit::script::Module>; _Args = {std::shared_ptr<torch::jit::script::Module>}]’
/usr/include/c++/6/bits/shared_ptr.h:635:39:   required from ‘std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = torch::jit::script::Module; _Args = {std::shared_ptr<torch::jit::script::Module>}]’
/home/weilo/Videos/alpha-zero-gomoku/src/libtorch.cpp:11:95:   required from here
/usr/include/c++/6/ext/new_allocator.h:120:4: error: no matching function for call to ‘torch::jit::script::Module::Module(std::shared_ptr<torch::jit::script::Module>)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/weilo/Videos/libtorch/include/torch/csrc/jit/import.h:4:0,
                 from /home/weilo/Videos/libtorch/include/torch/script.h:6,
                 from /home/weilo/Videos/alpha-zero-gomoku/./src/libtorch.h:3,
                 from /home/weilo/Videos/alpha-zero-gomoku/src/libtorch.cpp:1:
/home/weilo/Videos/libtorch/include/torch/csrc/jit/script/module.h:135:3: note: candidate: torch::jit::script::Module::Module()
   Module()
   ^~~~~~
/home/weilo/Videos/libtorch/include/torch/csrc/jit/script/module.h:135:3: note:   candidate expects 0 arguments, 1 provided
^[[A^[[ACMakeFiles/_library.dir/build.make:119: recipe for target 'CMakeFiles/_library.dir/src/libtorch.cpp.o' failed
make[2]: *** [CMakeFiles/_library.dir/src/libtorch.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/_library.dir/all' failed
make[1]: *** [CMakeFiles/_library.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gms2009** [comment]
刚刚下载 pre-cxx 版本
https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-1.2.0.zip
可以了 谢谢
