### ISSUE TITLE
Segmentation fault on Ubuntu

### ISSUE THREAD

**Issue by qiqiguaitm** [hijkzzz/alpha-zero-gomoku#3]
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
ITER :: 1
Segmentation fault

**Comment by hijkzzz** [comment]
ALSA lib confmisc.c:768:(parse_card) cannot find card '0' 
是pygame找不到声卡报错，没有影响

Segmentation fault
我这边Windows MSVC编译上没有发现这个问题，应该不是程序逻辑导致越界访问
可能是GCC编译模式不是x64-Release或者LibTorch的动态链接库没有放到环境变量？

**Comment by qiqiguaitm** [comment]
Thread 0x00002b1a5b018700 (most recent call first):
  File "../build/library.py", line 710 in get_action_probs
  File Segmentation fault (core dumped)

**Comment by hijkzzz** [comment]
首先很抱歉因为我一直在Windows下面测试，然后自己也没有Ubuntu的机器，所以很多地方不太完善
这里的调用关系是get_action_probs-->simulate-->libtorch(torchscript预测)
因为我这边MSVC编译的版本连续运行4天都没有任何错误
所以很难看出哪里非法指针/越界了
大佬有空的话可以gdb跟踪调试一下，应该很容易定位具体的报错位置，无奈我只有Windows x64~
或许是程序不严谨+GCC/MSVC的一些差异，又或者预编译的LibTorch与Ubuntu上GCC的兼容性，我之前遇到一次段错误是因为LibTorch是Release版本而MSVC设置为debug版本导致。

**Comment by hijkzzz** [comment]
辛苦了，那就继续coredump直接定位到出错的行~~
fix一下就应该没问题了
mcts里面就一个锁 
可以把mcts.cpp 122行     std::lock_guard<std::mutex> lock(this->lock); 注释掉试试

**Comment by hijkzzz** [comment]
也许应该指定一下gcc选项 set(CMAKE_CXX_FLAGS "-pthread")

**Comment by Augustusmyc** [comment]
> 
> 
> 测试了下几个test.cpp，libtorch_test,thread_pool_test都没问题。看infer的中间结果也ok，说明libtorch没有问题
> mcts_test运行会挂掉，gdb跟进了一下，发现，看起来是是锁的问题：
> Thread 6 "mcts_test" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffa0626700 (LWP 21672)]
> __GI___pthread_mutex_lock (mutex=0x28) at ../nptl/pthread_mutex_lock.c:67
> 67 ../nptl/pthread_mutex_lock.c: No such file or directory.
> (gdb)

你好，请问这个问题后来解决了么？我也遇到类似的问题了

**Comment by Augustusmyc** [comment]
> 
> 
> 测试了下几个test.cpp，libtorch_test,thread_pool_test都没问题。看infer的中间结果也ok，说明libtorch没有问题
> mcts_test运行会挂掉，gdb跟进了一下，发现，看起来是是锁的问题：
> Thread 6 "mcts_test" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffa0626700 (LWP 21672)]
> __GI___pthread_mutex_lock (mutex=0x28) at ../nptl/pthread_mutex_lock.c:67
> 67 ../nptl/pthread_mutex_lock.c: No such file or directory.
> (gdb)
@qiqiguaitm 
你好，请问后来这个问题有解决么？我遇到类似的情况了
