### ISSUE TITLE
关于mcts并行的一些困惑

### ISSUE THREAD

**Issue by ojbk888** [hijkzzz/alpha-zero-gomoku#30]
作者您好，我想问一下您的mcts并行大概是如何实现的？线程之间virtual loss是怎么传递的？与人对弈是也是采取batch预测的方式吗？ 感谢您的帮助

**Comment by hijkzzz** [comment]
你好，我在这里有简单的介绍
https://github.com/hijkzzz/alpha-zero-gomoku/wiki/%E5%8A%A8%E6%89%8B%E5%AE%9E%E7%8E%B0%E5%B9%B6%E8%A1%8C%E7%89%88AlphaZero

与人对弈也是batch预测的方式。

**Comment by ojbk888** [comment]
十分感谢
