### ISSUE TITLE
一些开源许可证方面的咨询

### ISSUE THREAD

**Issue by Ma-Weijian** [hijkzzz/alpha-zero-gomoku#31]
您好。

您的项目提供了一个非常优秀且高性能的五子棋智能体训练基线。阅读您的项目，对理解蒙特卡洛树搜索等AlphaZero中使用到的技术有很大的帮助。

我在您的项目的基础上，增加了例如联盟训练等等一些其他训练方法的实现。想问一下，我可否以MIT许可证的方式，使用您的项目的代码，并将我的实现开源。

非常感谢！

**Comment by hijkzzz** [comment]
非常欢迎自由使用/引用代码~谢谢

**Comment by Ma-Weijian** [comment]
好的，非常感谢！
