### ISSUE TITLE
buffer_len

### ISSUE THREAD

**Issue by qiqiguaitm** [hijkzzz/alpha-zero-gomoku#6]
'examples_buffer_max_len': 20,    

why so small?  in alphazero paper, it's 500000 games.

**Comment by hijkzzz** [comment]
it is 20 eps, 20 * 20 == 400 games.

**Comment by hijkzzz** [comment]
it is 20 iter, not 20 games

**Comment by hijkzzz** [comment]
It is 20 iters, not 20 games.And, faster sample updates speed up model convergence.
