### ISSUE TITLE
编译运行遇到错误了，麻烦帮忙看下

### ISSUE THREAD

**Issue by zfavourite99** [hijkzzz/alpha-zero-gomoku#9]
![image](https://user-images.githubusercontent.com/2630290/59962407-a6fe9780-9517-11e9-84d6-53f9cc000f31.png)
你好，请教一下，我clone你的源代码，从头编译，然后训练就会报这个错。
但是我下载你release里面的包，运行训练就没有问题，这个是啥情况引起的呢？

**Comment by zfavourite99** [comment]
问题解决了，cmake --build 生成的会报错，用vs打开library项目，在vs里面生成出来的库用着就没问题了

**Comment by hijkzzz** [comment]
好吧~
